//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Player.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PLAYER_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDI_PLAY_ENABLE                 131
#define IDI_PLAY_DISABLE                132
#define IDI_PLAY_CHECK                  133
#define IDI_PAUSE_ENABLE                134
#define IDI_PAUSE_DISABLE               135
#define IDI_PAUSE_CHECK                 136
#define IDI_STOP_ENABLE                 137
#define IDI_STOP_DISABLE                138
#define IDI_STOP_CHECK                  139
#define IDI_GOTOSTART_ENABLE            140
#define IDI_GOTOSTART_DISABLE           141
#define IDI_FASTBACKWARD_ENABLE         142
#define IDI_FASTBACKWARD_DISABLE        143
#define IDI_FASTFORWARD_ENABLE          144
#define IDI_FASTFORWARD_DISABLE         145
#define IDI_GOTOEND_ENABLE              146
#define IDI_GOTOEND_DISABLE             147
#define IDI_STEPBACKWARD_ENABLE         148
#define IDI_STEPBACKWARD_DISABLE        149
#define IDI_STEPFORWARD_ENABLE          150
#define IDI_STEPFORWARD_DISABLE         151
#define IDI_CAPPIC_ENABLE               152
#define IDI_CAPPIC_DISABLE              153
#define IDI_CAPPIC_AT                   154
#define IDI_SOUND_ENABLE                155
#define IDI_SOUND_DISABLE               156
#define IDB_BLACK                       181
#define IDB_HIKVISION                   182
#define IDB_OVERLAY                     183
#define IDD_INFO                        192
#define IDD_SEEK                        193
#define IDD_CUTFILE                     194
#define IDD_RANGE                       195
#define IDD_VIDEOCTRL                   219
#define IDI_BRIGHTNESS                  220
#define IDI_CONTRAST                    221
#define IDI_HUE                         222
#define IDI_SATURATION                  223
#define IDI_VIDEOCTRL                   224
#define IDD_APP_HELP                    225
#define IDB_VERTICAL_SCROLLBAR_UPARROW  226
#define IDB_HORIZONTAL_SCROLLBAR_CHANNEL 227
#define IDB_HORIZONTAL_SCROLLBAR_LEFTARROW 228
#define IDB_HORIZONTAL_SCROLLBAR_RIGHTARROW 229
#define IDB_HORIZONTAL_SCROLLBAR_THUMB  230
#define IDB_HORIZONTAL_SCROLLBAR_THUMB_NO_COLOR 231
#define IDB_VERTICAL_SCROLLBAR_CHANNEL  232
#define IDB_VERTICAL_SCROLLBAR_DOWNARROW 233
#define IDB_VERTICAL_SCROLLBAR_THUMB    234
#define IDB_VERTICAL_SCROLLBAR_THUMB_NO_COLOR 235
#define IDB_BITMAP_PLUS                 238
#define IDB_BITMAP_MINUS                239
#define IDD_WATERMARK                   240
#define IDC_CURSOR1                     241
#define IDD_SET_KEY                     242
#define IDC_VER                         1025
#define IDC_REFRESH                     1026
#define IDC_SEEK                        1026
#define IDC_SAVE                        1026
#define IDC_DISPLAY                     1026
#define IDC_INFOTEXT                    1027
#define IDC_BYFRAME                     1028
#define IDC_BYTIME                      1029
#define IDC_VALUE                       1030
#define IDC_RANGE                       1031
#define IDC_BEGIN                       1032
#define IDC_END                         1034
#define IDC_VIEW                        1035
#define IDC_REAL_BEGIN                  1036
#define IDC_REAL_END                    1037
#define IDC_FILENAME                    1038
#define IDC_DISWND                      1043
#define IDC_LIST_INFO                   1053
#define IDC_VC_BRIGHTNESS               1065
#define IDC_VC_CONTRAST                 1066
#define IDC_VC_SATURATION               1067
#define IDC_VC_HUE                      1068
#define IDC_SLIDER_BRIGHTNESS           1069
#define IDC_SLIDER_CONTRAST             1070
#define IDC_SLIDER_SATURATION           1071
#define IDC_SLIDER_HUE                  1072
#define IDC_VC_RESET                    1073
#define IDC_SLIDER1                     1074
#define IDC_MAC                         1074
#define IDC_STATIC_SIZE                 1075
#define IDC_DEVICESN                    1075
#define IDC_CHAN                        1076
#define IDC_EDIT_SIZE                   1077
#define IDC_GLOBALTIME                  1077
#define IDC_STATIC_MINUS                1078
#define IDC_DEVICEINFO                  1078
#define IDC_STATIC_PLUS                 1079
#define IDC_DEVICETYPE                  1079
#define IDC_STATIC_PST                  1080
#define ID_STATIC                       1080
#define IDC_CB_FORMAT                   1081
#define IDC_CB_LENGTH                   1082
#define IDC_RAD_ASCII                   1083
#define IDC_RAD_HEX                     1084
#define IDC_EDT_KEY                     1085
#define IDC_SHOW                        1201
#define IDC_PLAY                        1202
#define IDC_PAUSE                       1203
#define IDC_STOP                        1204
#define IDC_GOTOSTART                   1205
#define IDC_SLOW                        1206
#define IDC_FAST                        1207
#define IDC_GOTOEND                     1208
#define IDC_STEP                        1209
#define IDC_STEPBACK                    1210
#define IDC_CAPPIC                      1211
#define IDC_SOUND                       1212
#define IDC_INTER1                      1213
#define IDC_INTER2                      1214
#define IDC_INTER3                      1215
#define IDC_PLAY_SLIDER                 1216
#define IDC_PLAY_RECT_SLIDER            1217
#define IDC_SOUND_SLIDER                1218
#define IDC_PLAYSTATETEXT               1222
#define IDM_VIEW_FULLSCREEN             32775
#define IDM_VIEW_ZOOM_50                32777
#define IDM_VIEW_ZOOM_100               32778
#define IDM_VIEW_ZOOM_200               32779
#define IDM_REPEAT                      32781
#define IDM_QUALITY                     32782
#define IDM_STREAM_TYPE                 32783
#define IDM_INFO                        32784
#define IDM_SEEK                        32785
//#define IDM_CUT_FILE                    32786
#define IDM_THROW0                      32787
#define IDM_THROW1                      32788
#define IDM_THROW2                      32789
#define IDM_DECODE_NORMAL               32790
#define IDM_DECODE_I                    32791
#define IDM_DECODE_NONE                 32792
#define IDM_DISNORMAL                   32793
#define IDM_DISQUARTER                  32794
#define IDM_SETDISPLAY                  32795
#define IDM_TIMER1                      32796
#define IDM_TIMER2                      32797
#define IDM_RESET_BUF                   32798
//#define IDM_CONVERT                     32799
#define IDM_CAP_BMP                     32800
#define IDM_CAP_JPEG                    32801
#define IDM_CAPPIC_PATH                 32802
#define IDM_DEFLASH                     32803
#define IDM_SHARPEN_NONE                32808
#define IDM_SHARPEN_LEVEL1              32809
#define IDM_SHARPEN_LEVEL2              32810
#define IDM_SHARPEN_LEVEL3              32811
#define IDM_SHARPEN_LEVEL4              32812
#define IDM_SHARPEN_LEVEL5              32813
#define IDM_SHARPEN_LEVEL6              32814
#define IDM_FILE_OPEN                   32818
#define IDM_FILE_CLOSE                  32819
#define IDM_APP_EXIT                    32820
#define IDM_APP_ABOUT                   32822
#define IDM_VIDEO_CONTROL               32823
#define IDM_PLAY_PAUSE                  32824
#define IDM_STOP                        32825
#define IDM_STEPFORWARD                 32826
#define IDM_STEPBACKWARD                32827
#define IDM_GOTOEND                     32828
#define IDM_GOTOSTART                   32829
#define IDM_APP_HELP                    32830
#define IDM_PREVIEW50                   32831
#define IDM_TEMP_DEVICE                 32832
#define IDM_DEVICE0                     32833
#define IDM_DEVICE1                     32834
#define IDM_DEVICE2                     32835
#define IDM_DEVICE3                     32836
#define IDM_WATERMARK                   32838
#define IDM_SET_KEY                     32839

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        243
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
